### ISSUE TITLE
Nessun controller issue: ImportError: Cannot import module 'applications.test.modules.requests'

### ISSUE THREAD

**Issue by asiastitch** [KvasirSecurity/Kvasir#184]
Hi,

Please find below the issue about nessus controller configuration:

Traceback (most recent call last):
  File "/opt/web2py/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/opt/web2py/applications/test/controllers/nessus.py", line 244, in <module>
  File "/opt/web2py/gluon/globals.py", line 417, in <lambda>
    self._caller = lambda f: f()
  File "/opt/web2py/gluon/tools.py", line 4258, in f
    return action(*a, **b)
  File "/opt/web2py/applications/test/controllers/nessus.py", line 59, in import_scan
    from skaldship.nessus.ness6api import Nessus6API
  File "/opt/web2py/gluon/custom_import.py", line 95, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
  File "/opt/web2py/gluon/custom_import.py", line 134, in __call__
    result = NATIVE_IMPORTER(name, globals, locals, fromlist, level)
  File "applications/test/modules/skaldship/nessus/ness6api.py", line 12, in <module>
    import requests
  File "/opt/web2py/gluon/custom_import.py", line 89, in custom_importer
    raise ImportError, 'Cannot import module %s' % str(e)
ImportError: Cannot import module 'applications.test.modules.requests'

Thanks for your support!!!

**Comment by asiastitch** [comment]
Solved, 

pip install requests
